@ProjectLog.Api_HostAddress = http://localhost:5137

GET {{ProjectLog.Api_HostAddress}}/api/Projects
Accept: application/json

###

GET {{ProjectLog.Api_HostAddress}}/api/Projects/65cbbeb2-41ff-42dc-910e-3a837891accc
Accept: application/json

###

POST {{ProjectLog.Api_HostAddress}}/api/Projects
Content-Type: application/json
{
  "name": "Project 2",
  "description": "Description for Project 2"
}

###

PUT {{ProjectLog.Api_HostAddress}}/api/Projects/7d6e97cb-1e19-4fa2-becc-5774ef6fbb62
Content-Type: application/json
{
  "id": "7d6e97cb-1e19-4fa2-becc-5774ef6fbb62",
  "name": "Project 3",
  "description": "Description for Project 2",
  "createdAt": "2014-09-15T23:14:25.7251173",
  "tags": []
}

###

DELETE {{ProjectLog.Api_HostAddress}}/api/Projects/52695011-e807-423a-bcf6-c99f39324289

###